on:
  push:
    branches:
      - master

name: CICD Azure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY_NAME: cicdtestingregistry
      APP_NAME: cicd-web-app

    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/:${{ github.sha }}
          docker push mycontainer.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: '${{ env.APP_NAME }}'
          images: '${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}'

      - name: Azure logout
        run: |
          az logout
