on:
  push:
    branches:
      - master

name: CICD Azure

permissions:
  id-token: write
  contents: read

env:  
  REGISTRY_NAME: cicdtestingregistry
  APP_NAME: cicd-testing
  CONTAINER_NAME: cicd-container-app
  RESOURCE_GROUP : cicd-resource-group


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          # creds: ${{ secrets.AZURE_CREDS }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
          docker push  ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}

      # - uses: azure/webapps-deploy@v2     //deploy image azure app service
      #   with:
      #     app-name: '${{ env.APP_NAME }}'
      #     images: '${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}'

      - name: Azure logout
        run: |
          az logout


  deploy:
    runs-on: ubuntu-latest
      
    steps:
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          # creds: ${{ secrets.AZURE_CREDS }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: 'Deploy Container App'
      #   uses: Azure/cli@v1
      #   with:
      #     inlineScript: |
      #       echo "Installing containerapp extension"
      #       az extension add --source https://workerappscliextension.blob.core.windows.net/azure-cli-extension/containerapp-0.2.0-py2.py3-none-any.whl --yes
      #       echo "Starting Deploying"
      #       az containerapp update -n velidabookstoreapi -g todocontainerapp-rg -i ${{ secrets.REGISTRY_LOGIN_SERVER }}/bookstoreapi:${{ github.sha }} --registry-login-server ${{ secrets.REGISTRY_LOGIN_SERVER }} --registry-username  ${{ secrets.REGISTRY_USERNAME }} --registry-password ${{ secrets.REGISTRY_PASSWORD }} --debug

      - name: 'Deploy Container App'
        uses: Azure/cli@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ${{ env.REGISTRY_NAME }} -g ${{ env.RESOURCE_GROUP }} --server ${{ env.REGISTRY_NAME }}.azurecr.io --username  ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }}
            az containerapp update -n ${{ env.CONTAINER_NAME }} -g ${{ env.RESOURCE_GROUP }} --image ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}

      - name: Azure logout
        run: |
          az logout